### ISSUE TITLE
when 1.20.6 or 1.21?

### ISSUE THREAD

**Issue by Incluuu** [magemonkeystudio/illusion#3]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

when 1.20.6 or 1.21?

### How to reproduce

when 1.20.6 or 1.21?

### Server version

when 1.20.6 or 1.21?

### Holographic Displays version

when 1.20.6 or 1.21?

### Installed plugins that allow players to join with multiple Minecraft versions

when 1.20.6 or 1.21?

### Additional information

when 1.20.6 or 1.21?

**Comment by Travja** [comment]
A 1.21 version is available on our Discord
